# Numpy 

In [1]:
import numpy as np

**create an empty array of 20 0's and replace 4 th object with number 5**

In [9]:
# create an array of 20 0s
a=np.zeros(20)
a

# replace 4th object with number 5
a[3]=5           # index is 3 it starts from 0 
a

array([0., 0., 0., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

**create an empty array of 20 1's and store it as variable name array_master.copy same array into another variable**

In [13]:
array_master=np.ones(20)
array_master

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [16]:
# copy to another variable
array_copy=array_master.copy()
array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

**Create an array of 30 1s and broadcast all the ones to value 100**

In [19]:
Array=np.ones(30)
Array


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
# brodcast all ones to value 100 
Array[:] = 100
Array

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

Create an array of integers starting from 21 until 31 and name it A1


In [24]:
A1=np.arange(21,32)
A1

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

Create an array of integers starting from 11 until 21 and name it A2

In [28]:
A2=np.arange(11,22)
A2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

Calculate the difference between array1 and array2

In [30]:
DIFF=A1-A2
DIFF

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

Create an array of all even integers from 2 to 10 and name it a1

In [32]:
a1=np.arange(2,11,2)
a1

array([ 2,  4,  6,  8, 10])

Create an array of all even integers from 22 to 30 and name it a2

In [33]:
a2=np.arange(22,31,2)
a2

array([22, 24, 26, 28, 30])

# Use the 2 arrays as rows and create a matrix 

**for creating matrix from rows of array we use stack function of numpy**

In [34]:
# we used above a1 and a2 array
np.stack((a1,a2))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

# Use the 2 arrays as columns and create a matrix

**Use column_stack function from numpy** 

In [44]:
np.column_stack((a1,a2))

array([[ 0,  1,  2,  3,  4,  5, 22],
       [ 6,  7,  8,  9, 10, 11, 24],
       [12, 13, 14, 15, 16, 17, 26],
       [18, 19, 20, 21, 22, 23, 28],
       [24, 25, 26, 27, 28, 29, 30]])

Create a 5x6 matrix with values ranging from 0 to 29  and retrieve the value intersecting at 2nd row and 3rd column

In [47]:
a1=np.arange(0,30).reshape(5,6)
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [49]:
#retrieve the value intersecting at 2nd row and 3rd column
a1[1,2]

8

Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [51]:
# creating identity matrix we used eye
array=np.eye(10)
array

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

 replace the 0's with the value 21

In [52]:
array[array == 0] = 21
array

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

Use NumPy to generate a random set of 10 numbers between 0 and 1

In [59]:
b1=np.random.rand(10)
b1


array([0.46545557, 0.30187756, 0.87780965, 0.15101266, 0.11795919,
       0.85033369, 0.99289967, 0.05066875, 0.38046032, 0.94469282])

Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [58]:
b1>0.2

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True])

Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

In [76]:
a4=np.random.randn(5,2)
a4

array([[ 1.23543409, -0.48587117],
       [-0.87062799, -0.54259791],
       [ 0.62387761, -0.21044883],
       [-0.00993647,  1.14530119],
       [-0.40822756,  0.23775716]])

### Create an array of 30 linearly spaced points between 0 and 100

In [77]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

# Numpy Indexing and Selections

In [ ]:
create a simple matrix of 10x10 number from 1 to 100

In [81]:
simple_matrix= np.arange(1,101).reshape(10,10)
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

### a) Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [82]:
simple_matrix[8:,0:3]

array([[81, 82, 83],
       [91, 92, 93]])

### b) Retrieve the value 55 from the above matrix using index & selection technique

In [84]:
simple_matrix[5,4]

55

#### c) Retrieve the values from the 3rd column in the above matrix

In [87]:
simple_matrix[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

#### d) Retrieve the values from the 4th row in the above matrix

In [89]:
simple_matrix[3,:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

#### Retrieve values from the 2nd & 4th rows in the above matrix

In [93]:
simple_matrix[(1,3),:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

## Calculate the following values for the given matrix

### a) Calculate sum of all the values in the matrix

In [94]:
simple_matrix.sum()

5050

### b) Calculate standard deviation of all the values in the matrix

In [95]:
simple_matrix.std()

28.86607004772212

### c) Calculate the variance of all values in the matrix

In [96]:
simple_matrix.var()

833.25

### d) Calculate the mean of all values in the matrix

In [97]:
simple_matrix.mean()

50.5

### e) Retrieve the largest number from the matrix

In [98]:
simple_matrix.max()

100

### f) Retrieve the smallest number from the matrix

In [99]:
simple_matrix.min()

1